### PR TITLE
Allow escaped quotes

### PR DESCRIPTION
**Pull request by Valc**
Due now escaped quotes are allowed is not required alert about it use.
Please, test it.
[Edited]
Puf, i was trying to use the online "update files" to send pull requests and now i have noticed that this feature dump all the file as new.
To allow escaped quotes i simply have added this code after line 1350:
```
$cleaned = preg_replace('/"_QQ_"/', 'MOD_CATCHED_Q_', $unquoted_trimmed_value);
//Due now is allowed use escaped quotes this one will help to not throw an error when used.
$cleaned = preg_replace('/\\"/', 'MOD_CATCHED_ESCAPED_QUOTES', $cleaned);
//Now "$cleaned" have out the escaped quotes and only other wrong double quotes usage will be under revison.
```
 So, if you wanna apply the change without use this pull request, perfect.

Regards.

### CODE REVIEW

**Comment by infograf768** [comment]
@Valc I tested.
Indeed no more errors when using escaped double quotes but I do not get an error if I have
`COM_CONTENT_NUMBER_CATEGORY_ITEMS_LABEL="Nombre "_QQ"d'articles"`

When I var_dump $cleaned, I get
`string(72) "Nombre MOD_CATCHED_ESCAPED_QUOTES_QQMOD_CATCHED_ESCAPED_QUOTESd'articles"`

**Comment by infograf768** [comment]
@Valc 
The following solution works here
Replacing all` \"` to `"_QQ_"` earlier in the process works here.

Adding line 1236: 
`$trimmed_value           = str_replace('\"', '"_QQ_"', $trimmed_value);`

which means that block would look like
```
		elseif (strpos($line, '='))
		{
			$first_key_catched = '1';
			list($key, $value) = explode('=', $line, 2);
			$trimmed_key             = trim($key);
			$trimmed_value           = trim($value);
			$trimmed_value           = str_replace('\"', '"_QQ_"', $trimmed_value);
			$trimmed_value_Q_cleaned = preg_replace('/"_QQ_"/', '', $trimmed_value);
etc.
```
I rightfully get
screen shot 2018-03-31 at 08 18 38

**Comment by Valc** [comment]
@infograf768 
Let me take a look due i imagine than the escaped quotes needs to be reverted as escaped quotes again one time the test is done.

**Comment by Valc** [comment]
@infograf768 
Yeah, you have solved rightly. Is no mater in that part of source code if escaped quotes become as "_QQ_".
I think you can apply the patch.
Regards.

**Comment by infograf768** [comment]
Tks, will do.
We in fact use the same trick in com_localise + we do save any ini files with `\"` instead of `"_QQ_"`

**Comment by infograf768** [comment]
Corrected, Thus closing this.

**Pull request closed without merging**
